language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm install node-sass fur -g
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "BPgq0c3+mMYZSF27cp98FV348CiqrHnTNT4Z86+eNJSanCa8C31n8cjb0L1rWf9PIpAiB0Ap0LJhkuTwDoLyWtVB0xY5rnniHb90AuJ+bsVNfuSMtG4ueEdM2myJ+1WHxGfbKBKn165zZ+hPkUNiobSH+zVBgFNC3kyft0Ql+JTTNBX0QefOzLtc8hd4ivKspzTUl71xSct97SdrKsYjS/XQTszwn83CrqSEn/IXwyZornBqRtzrqquPq2HkC19UFzg4m3GtW56cjW2DTpfwQJ+FIfSgtq7Tnt9qr0z8UxBdnbZ6H+e66HF6YuesF2Z4XY7fUyb+DAgUOf1f+n/RZFufxl2ja0cu04gLbGbkruEAPaEa8rJFPx04p3rKn/ij8+oiMN+ZZ15jGB1ZkQ6Oe9Oxiiu1y6MAWbbz1uaZxjHGTkR/oZVgWMX93fuA54opZSXefacER5pLVosXSGgfeRU7uUWYzdcyHcfrZkeUCXjsCa4ABYwPknqGqDCd/G658ilY3sPAXZy5E7LQ08+U62u4TxrFjPaLb4XSzkbhauHkGkMmeptuS3D44/Ib4K16c2hAMIakt9mx53N9D4nPcolLdwLEJv7AEEaKPrcPgRaN9x5g14QHXL4yXBIgBO05RHdkueyzD63FDZpUU0Ux+HkqqYX0kOqxKiQPS3f7Bms="
